# Generated by Django 4.2.13 on 2024-05-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_on'], 'verbose_name': 'Contact Us Query', 'verbose_name_plural': 'Contact Us Queries'},
        ),
    ]
