# Generated by Django 4.2.13 on 2024-05-25 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_post_suggested_riding_ability_upvote_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='old_downvotes',
            field=models.ManyToManyField(blank=True, related_name='old_post_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='old_upvotes',
            field=models.ManyToManyField(blank=True, related_name='old_post_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
