# Generated by Django 4.2.13 on 2024-05-25 13:25
from django.db import migrations, models

def populate_upvote_downvote(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')  
    Upvote = apps.get_model('blog', 'Upvote')
    Downvote = apps.get_model('blog', 'Downvote')

    for post in Post.objects.all():
        for user in post.old_upvotes.all():
            Upvote.objects.create(user=user, post=post)
        for user in post.old_downvotes.all():
            Downvote.objects.create(user=user, post=post)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_old_downvotes_post_old_upvotes'),
    ]

    operations = [
        migrations.RunPython(populate_upvote_downvote),
    ]