# Generated by Django 4.2.13 on 2024-05-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240525_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='old_downvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='old_upvotes',
        ),
    ]
