# Generated by Django 4.2.13 on 2024-05-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_suggested_riding_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
