# Generated by Django 4.2.13 on 2024-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Open Suggestion'), (1, 'Published')], default=0),
        ),
    ]
