# Generated by Django 4.2.13 on 2024-05-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_rename_post_createpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
