# Generated by Django 4.2.13 on 2024-05-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_alter_createpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
