# Generated by Django 4.2.13 on 2024-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_createpost_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
